# https://taskfile.dev

version: '3'

tasks:
  install-deps:
    sources:
      - requirements.txt
    cmds:
      - python3 -m pip install -r requirements.txt
  build:
    deps:
      - install-deps
    sources:
      - templates/*.j2
      - data.yaml
    generates:
      - public
    cmds:
      - mkdir -p public
      - python3 generate.py
      - cp logo-placeholder.svg public/

  default:
    - task: build
